name: pubspec_lock_merge_driver
version: 0.1.0
description: A custom git merge driver for pubspec.lock files
repository: https://github.com/matthewnitschke/pubspec_lock_merge_driver

environment:
  sdk: '>=2.12.0 <3.0.0'

executables: 
  pubspec_lock_merge_driver: main

dependencies:
  args: ^2.3.1
  json2yaml: ^3.0.0
  pub_semver: ^2.1.1
  pubspec_lock_parse: ^2.1.0

dev_dependencies: 
  test: ^1.21.4
