name: pubspec_lock_merge_driver
version: 1.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.3.1
  json2yaml: ^3.0.0
  pub_semver: ^2.1.1
  pubspec_lock_parse: ^2.0.1


dependency_overrides:
  pubspec_lock_parse:
    path: ../../Repos/Personal/pubspec_lock_parse
dev_dependencies: {test: ^1.21.4}
